spring:
  datasource:
    url: jdbc:mysql://localhost:3306/raffle?useUnicode=true&characterEncoding=UTF-8&serverTimezone=CST&useSSL=false&allowPublicKeyRetrieval=true
    username: raffle
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 9091